title: Shay's Space
include: ["_pages"]
baseurl: ""
use_html_extension: false
open_external_links_in_new_tab: true
embed_tweets: false

permalink: pretty
relative_permalinks: false

plugins:
  - jekyll-last-modified-at
  - liquid_reading_time

sass:
  sass_dir: _sass
  style: :compressed

collections:
  notes:
    output: true
    permalink: /:slug

defaults:
  - scope:
      path: "**/*"
    values:
      layout: "default"
  - scope:
      path: "_notes/**/*.md"
    values:
      layout: "note"
  - scope:
      type: topics
    values:
      layout: topic
      permalink: topics/:topic/
