### SEO ###
title: "Shay's Space"
url: "https://shays.space"
tagline: "Ideas, essays, and projects by Shay Sayed."
description: "Ideas, essays, and projects by Shay Sayed. Writing about healthcare technology."
logo: "/assets/icon.png"
social:
  name: "Shaayaan Sayed"
  links:
    - https://www.linkedin.com/in/shaayaan-sayed-8097b1100/
    - https://twitter.com/ShaayaanS
    - https://github.com/shaayaansayed

include: ["_pages"]
use_html_extension: false
open_external_links_in_new_tab: true
embed_tweets: false

permalink: pretty

plugins:
  - jekyll-last-modified-at
  - liquid_reading_time
  - jekyll-seo-tag

sass:
  sass_dir: _sass
  style: :compressed

collections:
  notes:
    output: true
    permalink: /:slug

defaults:
  - scope:
      path: "**/*"
    values:
      layout: "default"
  - scope:
      path: "_notes/**/*.md"
    values:
      layout: "note"
  - scope:
      type: topics
    values:
      layout: topic
      permalink: topics/:topic/
